import * as fs from 'fs';
import * as path from 'path';

export interface AppRunInfo {
  hasPackageJson: boolean;
  appDir: string;
  installCmd: string;
  startCmd: string;
  startScript: string;
  scriptRelPath: string;
  oneLiner: string;
  hintUrl?: string;
}

export const RUN_APP_SCRIPT_REL = 'scripts/run-app.sh';

function pickStartScript(scripts: Record<string, string>): string {
  if (scripts.dev) return 'dev';
  if (scripts.start) return 'start';
  if (scripts.serve) return 'serve';
  return 'dev';
}

function guessDevUrl(scripts: Record<string, string>): string | undefined {
  const joined = Object.values(scripts).join(' ');
  if (/vite|5173/.test(joined)) return 'http://localhost:5173';
  if (/next|3000/.test(joined)) return 'http://localhost:3000';
  if (/nuxt|3000/.test(joined)) return 'http://localhost:3000';
  if (/4173/.test(joined)) return 'http://localhost:4173';
  return undefined;
}

/** Detect npm install + dev/start commands from the user app package.json. */
export function detectAppRunInfo(appDir: string): AppRunInfo {
  const resolved = path.resolve(appDir);
  const pkgPath = path.join(resolved, 'package.json');
  const hasPackageJson = fs.existsSync(pkgPath);
  let startScript = 'dev';
  let hintUrl: string | undefined;

  if (hasPackageJson) {
    try {
      const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8')) as { scripts?: Record<string, string> };
      const scripts = pkg.scripts || {};
      startScript = pickStartScript(scripts);
      hintUrl = guessDevUrl(scripts);
    } catch {
      startScript = 'dev';
    }
  }

  const installCmd = 'npm install';
  const startCmd = hasPackageJson ? `npm run ${startScript}` : 'npm run dev';
  const oneLiner = `${installCmd} && ${startCmd}`;

  return {
    hasPackageJson,
    appDir: resolved,
    installCmd,
    startCmd,
    startScript,
    scriptRelPath: RUN_APP_SCRIPT_REL,
    oneLiner,
    hintUrl,
  };
}

export function buildRunAppScriptContent(info: AppRunInfo): string {
  return `#!/usr/bin/env bash
# Install dependencies and start the app (generated by AWP Kanban)
set -euo pipefail
cd "$(dirname "$0")/.."
${info.installCmd}
${info.startCmd}
`;
}

/** Write scripts/run-app.sh in the user project if package.json exists and script is missing. */
export function ensureRunAppScript(appDir: string): AppRunInfo {
  const info = detectAppRunInfo(appDir);
  if (!info.hasPackageJson) return info;

  const scriptAbs = path.join(info.appDir, RUN_APP_SCRIPT_REL);
  if (!fs.existsSync(scriptAbs)) {
    fs.mkdirSync(path.dirname(scriptAbs), { recursive: true });
    fs.writeFileSync(scriptAbs, buildRunAppScriptContent(info), { mode: 0o755 });
  }
  return info;
}

export function formatCompletionRunBlock(info: AppRunInfo, kanbanPort: number): string {
  const lines = [
    `Kanban board: http://localhost:${kanbanPort}/`,
    `Backlog complete: http://localhost:${kanbanPort}/?backlog=complete`,
    `Time dashboard: http://localhost:${kanbanPort}/?dashboard=1`,
    '',
    'Run the app from project root:',
    `  cd ${info.appDir}`,
  ];
  if (info.hasPackageJson) {
    lines.push(`  ./${info.scriptRelPath}`);
    lines.push('  # or:');
    lines.push(`  ${info.oneLiner}`);
    if (info.hintUrl) lines.push(`  # App URL (typical): ${info.hintUrl}`);
  } else {
    lines.push('  # No package.json found — add one, then:');
    lines.push(`  ${info.oneLiner}`);
  }
  return lines.join('\n');
}
