"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.RUN_APP_SCRIPT_REL = void 0;
exports.detectAppRunInfo = detectAppRunInfo;
exports.buildRunAppScriptContent = buildRunAppScriptContent;
exports.ensureRunAppScript = ensureRunAppScript;
exports.formatCompletionRunBlock = formatCompletionRunBlock;
const fs = __importStar(require("fs"));
const path = __importStar(require("path"));
exports.RUN_APP_SCRIPT_REL = 'scripts/run-app.sh';
function pickStartScript(scripts) {
    if (scripts.dev)
        return 'dev';
    if (scripts.start)
        return 'start';
    if (scripts.serve)
        return 'serve';
    return 'dev';
}
function guessDevUrl(scripts) {
    const joined = Object.values(scripts).join(' ');
    if (/vite|5173/.test(joined))
        return 'http://localhost:5173';
    if (/next|3000/.test(joined))
        return 'http://localhost:3000';
    if (/nuxt|3000/.test(joined))
        return 'http://localhost:3000';
    if (/4173/.test(joined))
        return 'http://localhost:4173';
    return undefined;
}
/** Detect npm install + dev/start commands from the user app package.json. */
function detectAppRunInfo(appDir) {
    const resolved = path.resolve(appDir);
    const pkgPath = path.join(resolved, 'package.json');
    const hasPackageJson = fs.existsSync(pkgPath);
    let startScript = 'dev';
    let hintUrl;
    if (hasPackageJson) {
        try {
            const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
            const scripts = pkg.scripts || {};
            startScript = pickStartScript(scripts);
            hintUrl = guessDevUrl(scripts);
        }
        catch {
            startScript = 'dev';
        }
    }
    const installCmd = 'npm install';
    const startCmd = hasPackageJson ? `npm run ${startScript}` : 'npm run dev';
    const oneLiner = `${installCmd} && ${startCmd}`;
    return {
        hasPackageJson,
        appDir: resolved,
        installCmd,
        startCmd,
        startScript,
        scriptRelPath: exports.RUN_APP_SCRIPT_REL,
        oneLiner,
        hintUrl,
    };
}
function buildRunAppScriptContent(info) {
    return `#!/usr/bin/env bash
# Install dependencies and start the app (generated by AWP Kanban)
set -euo pipefail
cd "$(dirname "$0")/.."
${info.installCmd}
${info.startCmd}
`;
}
/** Write scripts/run-app.sh in the user project if package.json exists and script is missing. */
function ensureRunAppScript(appDir) {
    const info = detectAppRunInfo(appDir);
    if (!info.hasPackageJson)
        return info;
    const scriptAbs = path.join(info.appDir, exports.RUN_APP_SCRIPT_REL);
    if (!fs.existsSync(scriptAbs)) {
        fs.mkdirSync(path.dirname(scriptAbs), { recursive: true });
        fs.writeFileSync(scriptAbs, buildRunAppScriptContent(info), { mode: 0o755 });
    }
    return info;
}
function formatCompletionRunBlock(info, kanbanPort) {
    const lines = [
        `Kanban board: http://localhost:${kanbanPort}/`,
        `Completion report: http://localhost:${kanbanPort}/?completed=`,
        `Time dashboard: http://localhost:${kanbanPort}/?dashboard=1`,
        '',
        'Run the app from project root:',
        `  cd ${info.appDir}`,
    ];
    if (info.hasPackageJson) {
        lines.push(`  ./${info.scriptRelPath}`);
        lines.push('  # or:');
        lines.push(`  ${info.oneLiner}`);
        if (info.hintUrl)
            lines.push(`  # App URL (typical): ${info.hintUrl}`);
    }
    else {
        lines.push('  # No package.json found — add one, then:');
        lines.push(`  ${info.oneLiner}`);
    }
    return lines.join('\n');
}
